"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'cbzx^@c-0g0!nv1u7rf9wptznilook@25h*v*y1r62gm+!o2_#'
SESSION_COOKIE_NAME='rainfall_monitor'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ["*"]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
   'website'
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

SESSION_ENGINE = "django.contrib.sessions.backends.cache" 

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates').replace('\\', '/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', #因為你用的是MySQL
        'NAME': 'water monitor',                       
        'USER': 'root',                       #這裡用最高權限管理員
        'PASSWORD': '1234567=',            #你的密碼
        'HOST': 'localhost',                           #空白預設為localhost
        'PORT': '3306',                           #空白預設為DB port
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# session expire at browser close
#SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# wsgi scheme
#os.environ['wsgi.url_scheme'] = 'https'


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

# 静态文件的URL前缀
STATIC_URL = '/static/'

# 静态文件的根目录（用于收集静态文件）
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# 本地静态文件目录
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),  # 根目录下的静态文件目录
    ('css', os.path.join(BASE_DIR, 'static/css')),  # 单独的CSS目录
    ('js', os.path.join(BASE_DIR, 'static/js')),  # 单独的JS目录
    # ('images', os.path.join(BASE_DIR, 'static/images')),  # 单独的图片目录
    ('media', os.path.join(BASE_DIR, 'static/media')),  # 单独的媒体文件目录
    # 如果需要，可以解开注释，并添加其他目录
    # ('backend', os.path.join(BASE_DIR, 'static/backend')),
]

DATA_UPLOAD_MAX_MEMORY_SIZE =502428800
